# These are supported funding model platforms


# Ethereum address
Ethereum: "0x51bd25d89ff0bd5c1006187f7d4b7e6562db447c"

# Solana address
Solana: "3J4dh9j5J1mFggsJCnnjUc6WtQgeHFcALCuw7TALdwWc"

# Torn address
Torn: "TJJUPwmrLNnue2sqB7t2eutZXLkSoPs83s"

# X Layer address
X_Layer: "0x51bd25d89ff0bd5c1006187f7d4b7e6562db447c"

# Linea address
Linea: "0x51bd25d89ff0bd5c1006187f7d4b7e6562db447c"

# BNBChain address
BNBChain: "0x51bd25d89ff0bd5c1006187f7d4b7e6562db447c"

# Bitcoin address
Bitcoin: "bc1psq3vrdjdjwp6cklrhk2uvzetk5pzgx0stkehtk8mzsx3jfp6pcgsl43u47"

# WeChat account
WeChat微信: "MrCWhide"                               

# Bank card information
BankCard: "6212251208000593251"  # Only supports ATM     
